# Generated by Django 4.2.1 on 2023-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='blog_articl_publish_2a54df_idx',
            old_name='personal_bl_publish_0f90e9_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
